builds:
  - binary: cage
    main: ./cli/cage/main.go
    goos:
      - darwin
      - linux
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
git:
  tag_sort: semver
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: loilo-inc
    name: canarycage
