#!/bin/sh
# CircleCIで渡されるやつ
echo "# Passed from CircleCI"
echo AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
echo AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY}
echo AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY}
echo CODECOV_TOKEN=${CODECOV_TOKEN}
echo CI=$CI
echo CIRCLECI=$CIRCLECI
# echo HOME=$HOME
echo CIRCLE_BRANCH=$CIRCLE_BRANCH
echo CIRCLE_NODE_TOTAL=$CIRCLE_NODE_TOTAL
echo CIRCLE_NODE_INDEX=$CIRCLE_NODE_INDEX
echo CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM
echo CIRCLE_PREVIOUS_BUILD_NUM=$CIRCLE_PREVIOUS_BUILD_NUM
echo CIRCLE_BUILD_URL=$CIRCLE_BUILD_URL
echo CIRCLE_SHA1=$CIRCLE_SHA1
echo CIRCLE_USERNAME=$CIRCLE_USERNAME
echo CIRCLE_JOB=$CIRCLE_JOB
echo CIRCLE_WORKING_DIRECTORY=$CIRCLE_WORKING_DIRECTORY
echo CIRCLE_COMPARE_URL=$CIRCLE_COMPARE_URL
echo CIRCLE_REPOSITORY_URL=$CIRCLE_REPOSITORY_URL
echo CIRCLE_PR_NUMBER=$CIRCLE_PR_NUMBER
echo CIRCLE_PR_REPONAME=$CIRCLE_PR_REPONAME
echo CIRCLE_PR_USERNAME=$CIRCLE_PR_USERNAME
echo CIRCLE_PULL_REQUESTS=$CIRCLE_PULL_REQUESTS
echo CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST
echo CI_PULL_REQUESTS=$CI_PULL_REQUESTS
echo CI_PULL_REQUEST=$CI_PULL_REQUEST
echo CIRCLE_TAG=$CIRCLE_TAG
echo CIRCLE_PROJECT_USERNAME=$CIRCLE_PROJECT_USERNAME
echo CIRCLE_PROJECT_REPONAME=$CIRCLE_PROJECT_REPONAME
echo CIRCLE_INTERNAL_TASK_DATA=$CIRCLE_INTERNAL_TASK_DATA
echo CIRCLE_STAGE=$CIRCLE_STAGE
echo CIRCLE_WORKFLOW_ID=$CIRCLE_WORKFLOW_ID
