# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    machine:
      - docker_layler_caching: true
    working_directory: /go/src/github.com/loilo-inc/canarycage
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get -u github.com/keroxp/shake
      - run: shake test