# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/loilo-inc/canarycage
    steps:
      - checkout
      - run:
          Name: Install Dependencies
          Command: |
            go get -u github.com/keroxp/shake
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
      - run: go build
      - run: go build github.com/loilo-inc/canarycage/cli/cage
      - run: shake test