// Code generated by MockGen. DO NOT EDIT.
// Source: ./types/iface.go

// Package mock_types is a generated GoMock package.
package mock_types

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	types "github.com/loilo-inc/canarycage/types"
)

// MockCage is a mock of Cage interface.
type MockCage struct {
	ctrl     *gomock.Controller
	recorder *MockCageMockRecorder
}

// MockCageMockRecorder is the mock recorder for MockCage.
type MockCageMockRecorder struct {
	mock *MockCage
}

// NewMockCage creates a new mock instance.
func NewMockCage(ctrl *gomock.Controller) *MockCage {
	mock := &MockCage{ctrl: ctrl}
	mock.recorder = &MockCageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCage) EXPECT() *MockCageMockRecorder {
	return m.recorder
}

// RollOut mocks base method.
func (m *MockCage) RollOut(ctx context.Context, input *types.RollOutInput) (*types.RollOutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollOut", ctx, input)
	ret0, _ := ret[0].(*types.RollOutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RollOut indicates an expected call of RollOut.
func (mr *MockCageMockRecorder) RollOut(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollOut", reflect.TypeOf((*MockCage)(nil).RollOut), ctx, input)
}

// Run mocks base method.
func (m *MockCage) Run(ctx context.Context, input *types.RunInput) (*types.RunResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, input)
	ret0, _ := ret[0].(*types.RunResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockCageMockRecorder) Run(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCage)(nil).Run), ctx, input)
}

// Up mocks base method.
func (m *MockCage) Up(ctx context.Context) (*types.UpResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Up", ctx)
	ret0, _ := ret[0].(*types.UpResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Up indicates an expected call of Up.
func (mr *MockCageMockRecorder) Up(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Up", reflect.TypeOf((*MockCage)(nil).Up), ctx)
}

// MockTime is a mock of Time interface.
type MockTime struct {
	ctrl     *gomock.Controller
	recorder *MockTimeMockRecorder
}

// MockTimeMockRecorder is the mock recorder for MockTime.
type MockTimeMockRecorder struct {
	mock *MockTime
}

// NewMockTime creates a new mock instance.
func NewMockTime(ctrl *gomock.Controller) *MockTime {
	mock := &MockTime{ctrl: ctrl}
	mock.recorder = &MockTimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTime) EXPECT() *MockTimeMockRecorder {
	return m.recorder
}

// NewTimer mocks base method.
func (m *MockTime) NewTimer(arg0 time.Duration) *time.Timer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTimer", arg0)
	ret0, _ := ret[0].(*time.Timer)
	return ret0
}

// NewTimer indicates an expected call of NewTimer.
func (mr *MockTimeMockRecorder) NewTimer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTimer", reflect.TypeOf((*MockTime)(nil).NewTimer), arg0)
}
