// Code generated by MockGen. DO NOT EDIT.
// Source: ./cli/cage/audit/printer.go
//
// Generated by this command:
//
//	mockgen -source=./cli/cage/audit/printer.go
//

// Package mock_audit is a generated GoMock package.
package mock_audit

import (
	reflect "reflect"

	audit "github.com/loilo-inc/canarycage/cli/cage/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockPrinter is a mock of Printer interface.
type MockPrinter struct {
	ctrl     *gomock.Controller
	recorder *MockPrinterMockRecorder
	isgomock struct{}
}

// MockPrinterMockRecorder is the mock recorder for MockPrinter.
type MockPrinterMockRecorder struct {
	mock *MockPrinter
}

// NewMockPrinter creates a new mock instance.
func NewMockPrinter(ctrl *gomock.Controller) *MockPrinter {
	mock := &MockPrinter{ctrl: ctrl}
	mock.recorder = &MockPrinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrinter) EXPECT() *MockPrinterMockRecorder {
	return m.recorder
}

// Print mocks base method.
func (m *MockPrinter) Print(result []*audit.ScanResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Print", result)
}

// Print indicates an expected call of Print.
func (mr *MockPrinterMockRecorder) Print(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockPrinter)(nil).Print), result)
}

// PrintJSON mocks base method.
func (m *MockPrinter) PrintJSON(metadata audit.Target, scanResults []*audit.ScanResult) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintJSON", metadata, scanResults)
}

// PrintJSON indicates an expected call of PrintJSON.
func (mr *MockPrinterMockRecorder) PrintJSON(metadata, scanResults any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintJSON", reflect.TypeOf((*MockPrinter)(nil).PrintJSON), metadata, scanResults)
}
