@startuml

(*) --> "初期化"
 if "タスク定義ARNあり？" then
    --> [あり] "新規サービス作成"
else
    if "タスク定義あり？" then
        --> [YES] "タスク定義更新"
        --> "新規サービス作成"
    else
        --> [NO] "エラー"
    endif
endif
"新規サービス作成" --> if "サービス定義あり？" then
    --> [YES] "サービス定義からサービス作成"
    if エラー？
        --> [YES] エラー
    else
        --> [NO] "ロールアウト開始"
    endif

else
    --> [NO] "既存サービスのレプリカを作成"
    if エラー？
        --> [YES] エラー
    else
        --> [NO] "ロールアウト開始"
    endif
endif

"ロールアウト開始" -->  "新規サービスのdesiredCountを2^nに設定"
if "エラー？"
    --> [YES] ロールバック
else
    --> [NO] 検証期間待機
endif


"検証期間待機" --> "サービスヘルスを検証"

if "SLOを割っている？"
    --> [YES] ロールバック
else
    --> [NO] 既存サービスのdesiredCountを追加した分減らす
endif

既存サービスのdesiredCountを追加した分減らす --> if 既存サービスのdesiredCountが0？
    --> [YES] 最終検証期間待機
    --> "最終サービスヘルス検証"
else
    --> [NO] "新規サービスのdesiredCountを2^nに設定"
endif

"最終サービスヘルス検証" --> if "SLOを割っている？"
    --> [YES] ロールバック
else
    --> [NO] ロールアウト完了
endif

エラー --> (*)
ロールアウト完了 --> (*)
"ロールバック" --> "既存サービスのdesiredCountをロールアウト前に戻す"
--> "新規サービスのdesiredCountを0にする"
--> "新規サービスを消す"
--> (*)

@enduml